[versions]
accompanistSystemuicontroller = "0.36.0"
agp = "8.5.2"
androidutilslibrary = "1.0.0"
coil = "2.7.0"
coilCompose = "3.0.0-rc01"
coreSplashscreen = "1.0.1"
dexter = "6.2.3"
glide = "4.15.1"
gson = "2.11.0"
koinAndroid = "3.5.3"
koinAndroidxCompose = "3.5.3"
kotlin = "1.9.0"
coreKtx = "1.13.1"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
kpermissionsCoroutines = "3.5.0"
material = "1.12.0"
constraintlayout = "2.1.4"
lifecycleLivedataKtx = "2.8.6"
lifecycleViewmodelKtx = "2.8.6"
materialVersion = "1.7.3"
navigationCompose = "2.4.0-alpha01"
navigationFragmentKtx = "2.8.1"
navigationUiKtx = "2.8.1"
okhttp = "4.12.0"
permissionsdispatcherProcessor = "4.8.0"
photoview = "2.0.0"
photoviewVersion = "2.3.0"
picasso = "2.8"
picasso2Okhttp3Downloader = "1.1.0"
picassoTransformations = "2.4.0"
retrofit = "2.11.0"
retrofitVersion = "2.3.0"
splashy = "1.3.0"
swiperefreshlayout = "1.1.0"
touchimageview = "1.4.1"
ui = "1.0.0"
uiGraphicsAndroid = "1.7.3"
constraintlayoutCompose = "1.0.1"
library = "1.0.0"
runtimeLivedata = "1.7.1"
databindingCompiler = "8.7.0"
zoomable = "1.6.2"
zoomimageViewCoil = "1.0.0"
foundationLayoutAndroid = "1.7.2"
fragmentCompose = "1.8.4"


[libraries]
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanistSystemuicontroller" }
androidutilslibrary = { module = "com.gitlab.developerdeveloperdeveloper:androidutilslibrary", version.ref = "androidutilslibrary" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleLivedataKtx" }
androidx-material = { module = "androidx.compose.material:material", version.ref = "materialVersion" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationFragmentKtx" }
androidx-navigation-compose-v240alpha01 = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
androidx-ui = { module = "androidx.compose.ui:ui", version.ref = "uiGraphicsAndroid" }
androidx-ui-v100 = { module = "androidx.compose.ui:ui", version.ref = "ui" }
coil = { module = "io.coil-kt:coil", version.ref = "coil" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coilCompose" }
coil-network-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coilCompose" }
compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofitVersion" }
dexter = { module = "com.karumi:dexter", version.ref = "dexter" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koinAndroid" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koinAndroidxCompose" }
kpermissions-coroutines = { module = "com.github.fondesa:kpermissions-coroutines", version.ref = "kpermissionsCoroutines" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigationUiKtx" }
androidx-swiperefreshlayout = { group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref = "swiperefreshlayout" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
permissionsdispatcher = { module = "com.github.permissions-dispatcher:permissionsdispatcher", version.ref = "permissionsdispatcherProcessor" }
permissionsdispatcher-processor = { module = "com.github.permissions-dispatcher:permissionsdispatcher-processor", version.ref = "permissionsdispatcherProcessor" }
photoview = { module = "com.github.chrisbanes:PhotoView", version.ref = "photoview" }
photoview-v230 = { module = "com.github.chrisbanes:PhotoView", version.ref = "photoviewVersion" }
picasso = { module = "com.squareup.picasso:picasso", version.ref = "picasso" }
picasso-transformations = { module = "jp.wasabeef:picasso-transformations", version.ref = "picassoTransformations" }
picasso2-okhttp3-downloader = { module = "com.jakewharton.picasso:picasso2-okhttp3-downloader", version.ref = "picasso2Okhttp3Downloader" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-v230 = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofitVersion" }
androidx-ui-graphics-android = { group = "androidx.compose.ui", name = "ui-graphics-android", version.ref = "uiGraphicsAndroid" }
splashy = { module = "com.rbddevs.splashy:splashy", version.ref = "splashy" }
touchimageview = { module = "com.github.MikeOrtiz:TouchImageView", version.ref = "touchimageview" }
androidx-material3 = { module = "androidx.compose.material3:material3" }
ui = { module = "androidx.compose.ui:ui" }
androidx-adaptive = { module = "androidx.compose.material3.adaptive:adaptive" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-constraintlayout-compose = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraintlayoutCompose" }
library = { module = "me.zhanghai.compose.preference:library", version.ref = "library" }
androidx-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "runtimeLivedata" }
ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "uiGraphicsAndroid" }
androidx-databinding-compiler = { group = "androidx.databinding", name = "databinding-compiler", version.ref = "databindingCompiler" }
zoomable = { module = "net.engawapg.lib:zoomable", version.ref = "zoomable" }
zoomimage-view-coil = { module = "io.github.panpf.zoomimage:zoomimage-view-coil", version.ref = "zoomimageViewCoil" }
androidx-foundation-layout-android = { group = "androidx.compose.foundation", name = "foundation-layout-android", version.ref = "foundationLayoutAndroid" }
androidx-fragment-compose = { group = "androidx.fragment", name = "fragment-compose", version.ref = "fragmentCompose" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

